language: python
python:
  - "3.6"

install:
  - pip install -e .
  - pip install $DJANGO
  - pip install -r requirements.txt
script:
  - python runtests.py
env:
  - DJANGO="Django==1.10.*"
  - DJANGO="Django==1.11.*"
  - DJANGO="Django==2.0.*"
  - DJANGO="Django==2.2.*"


